CC		=	armv5te-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -lstdc++ -L. 

# for LD debug -s

OBJ					= bin/armv5te
EXECUTABLE 			= bin/squeeze2cast-armv5te
EXECUTABLE_STATIC 	= bin/squeeze2cast-armv5te-static

include Makefile

