CC=x86_64-cross-freebsd11-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lm -lrt -lstdc++ -L. 
#LDFLAGS ?= -s -lgomp -lpthread -ldl -lm -lrt -lstdc++ -L. 

OBJ					= bin/bsd-x64
EXECUTABLE 			= bin/squeeze2cast-bsd-x64
EXECUTABLE_STATIC	= bin/squeeze2cast-bsd-x64-static

include Makefile


