CC = powerpc-cross-linux-gnu-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lgomp -lpthread -lssl -lcrypto -ldl -lm -lrt -lstdc++ -L. 

OBJ					= bin/ppc
EXECUTABLE 			= bin/squeeze2cast-ppc
EXECUTABLE_STATIC	= bin/squeeze2cast-ppc-static

include Makefile

