CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lgomp -lpthread -lssl -lcrypto -ldl -lm -lrt -lz -lstdc++ -L. 
# for LD debug -s

OBJ					= bin/x86
EXECUTABLE 			= bin/squeeze2cast-x86
EXECUTABLE_STATIC 	= bin/squeeze2cast-x86-static

include Makefile

