CC	 	= armv6j-cross-linux-gnueabihf-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lssl -lcrypto -ldl -lm -lrt -lstdc++ -L. 
# for LD debug -s

OBJ					= bin/armv6hf
EXECUTABLE 			= bin/squeeze2cast-armv6hf
EXECUTABLE_STATIC 	= bin/squeeze2cast-armv6hf-static

include Makefile

